### 포스트잇 등록
POST http://localhost:8080/api/v1/postits/register
Content-Type: application/json

{
  "userToken": "user_1234",
  "content": "test-postIt3",
  "status": "INCOMPLETE",
  "categoryName" : "test-category"
}

### 포스트잇 대량 등록
POST http://localhost:8080/api/v1/postits/register/batch
Content-Type: application/json

{
  "registerRequestList" : [
    {
      "userToken": "user_1234",
      "content": "test-postIt2",
      "status": "INCOMPLETE",
      "categoryName" : "test-category1"
    },
    {
      "userToken": "user_1234",
      "content": "test-postIt2",
      "status": "INCOMPLETE",
      "categoryName" : "test-category2"
    }
  ]
}