### 프로젝트 등록
POST http://localhost:8080/api/v1/projects/register/project
Content-Type: application/json

{
  "userToken": "user_1234",
  "projectName": "test-project",
  "endDayTime": "22-10-10-15:00",
  "registerTaskList" : [
  ]
}

### 프로젝트 및 태스크 및 액션 등록
POST http://localhost:8080/api/v1/projects/register/project
Content-Type: application/json

{
  "userToken": "user_1234",
  "projectName": "test-project",
  "endDayTime": "22-10-10-15:00",
  "registerTaskList" : [
    {
      "taskName": "test-task",
      "importance" : "HIGH",
      "startDayTime" : "22-10-09-10:00",
      "endDayTime" : "22-10-09-14:00",
      "projectToken" : "",
      "registerActionList" : [
        {
          "content" : "test-action1"
        },
        {
          "content" : "test-action2"
        }
      ]
    }
  ]
}

### 프로젝트에 소속되지 않은 태스크 및 액션 등록
POST http://localhost:8080/api/v1/projects/register/task
Content-Type: application/json

{
  "taskName": "test--task-noneProject",
  "importance" : "HIGH",
  "startDayTime" : "22-10-09-10:00",
  "endDayTime" : "22-10-09-14:00",
  "projectToken" : "project_1234",
  "registerActionList" : [
    {
      "taskToken" : "",
      "content" : "test-action1"
    },
    {
      "taskToken" : "",
      "content" : "test-action2"
    }
      ]
}


### 태스크에 새로운 액션 추가
POST http://localhost:8080/api/v1/projects/register/action
Content-Type: application/json

{
  "taskToken" : "task_m3x5bD5MwL92q6L",
  "content" : "test-action"
}

### 프로젝트 업데이트 테스트
POST http://localhost:8080/api/v1/projects/update/project
Content-Type: application/json

{
  "userToken" : "user_1234",
  "projectToken" : "project_1234",
  "projectName" : "project-update test",
  "endDayTime" : null,
  "updateTaskList" : []
}

### 프로젝트와 태스크 업데이트 태스트
POST http://localhost:8080/api/v1/projects/update/project
Content-Type: application/json

{
  "userToken": "user_1234",
  "projectToken": "project_1234",
  "projectName": "project-update test2",
  "endDayTime": null,
  "updateTaskList": [
    {
      "taskToken": "",
      "taskName": "test-task-update",
      "importance": "MIDDLE",
      "startDayTime": "22-10-09-10:00",
      "endDayTime": "22-10-09-14:00",
      "projectToken": "project_1234",
      "updateActionList": [
        {
          "taskToken": "",
          "actionToken": "action_gb57IITqWFt8a",
          "content": "test-action1-update",
          "actionStatus": "DONE"
        },
        {
          "taskToken" : "",
          "actionToken" : "",
          "content" : "new-action-update",
          "actionStatus" : "UNDONE"
        }
      ]
    }
  ]
}

### 태스크 업데이트 태스트
POST http://localhost:8080/api/v1/projects/update/task
Content-Type: application/json

{
  "taskToken" : "task_WI3PF1nxRadVf2n",
  "projectToken" : "project_1234",
  "taskName": "test--task-update-new-name",
  "importance" : "HIGH",
  "startDayTime" : "22-10-09-10:00",
  "endDayTime" : "22-10-09-14:00",
  "updateActionList" : [
    {
      "taskToken" : "task_WI3PF1nxRadVf2n",
      "actionToken" : "action_207K0LZDVc3f0",
      "content" : "test-action1-update",
      "actionStatus" : "DONE"
    },
    {
      "taskToken" : "task_WI3PF1nxRadVf2n",
      "actionToken" : "action_riqwzTMXzfLr2",
      "content" : "test-action2-update",
      "actionStatus" : "DONE"
    },
    {
      "taskToken" : "task_WI3PF1nxRadVf2n",
      "actionToken" : "",
      "content" : "test-action3-update",
      "actionStatus" : "UNDONE"
    }
  ]
}

### 프로젝트 토큰으로 검색
POST http://localhost:8080/api/v1/projects/retrieve/project
Content-Type: application/json

{
  "projectToken": "project_1234"
}

